name: Tests

on:
  push:
    branches: [ "solution" ]
  pull_request:
    branches: [ "solution" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Test A1 with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: test
        build-root-directory: A1/tai-e
